### ISSUE TITLE
[FIX] 로그인 버그 디버깅

### ISSUE THREAD

**Issue by gyeongminK** [seohyun319/HanALL#108]
- [x] 로그인 시 쿠키가 2개 세팅되고 로그아웃이 적용되지 않는 버그 해결 #110
- [x] 로그인 비밀번호 틀린 경우 응답 200 나오는 버그 해결 #109
- [x] detailPage alert 로그인 분기 처리 해결 #114
- [x] 로그인 새로고침시 뷰 풀리는 문제 해결 #126
- [ ] 리덕스 로그인 정보 로컬 스토리지에서 세션 스토리지로 변경
